#!/bin/bash

module load buster/20211020
module load phenix/1.20
module load ccp4/7.1.018

export BDG_TOOL_MOGUL="/dls_sw/apps/ccdc/CSD_2020/bin/mogul"
export XChemExplorer_DIR="/dls_sw/i04-1/software/XChemExplorer"

if [ $1 = "setup" ]; then
    (cd $XChemExplorer_DIR; ccp4-python setup.py install --user)
fi

ccp4-python -m xce

